spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/petmily
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        #        -> system.out
        format_sql: true

  messages:
    basename: messages, errors

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.trace: trace
#    -> 콘솔

server:
  servlet:
    session:
      timeout: 1800
