spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/

  messages:
    basename: messages, errors, exception

server:
  servlet:
    session:
      timeout: 1800

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@petmily_medium?TNS_ADMIN=/home/petmily/Wallet_petmily
    username: ADMIN
    password: PetmilyProject123!

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 80

file:
  dir: /home/petmily/picture/
---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/petmily
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug

file:
  dir: /Users/joojongbum/Desktop/work/project/petmily/src/main/resources/static/picture/
---