spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://petmily.cyttrlbc5ek1.ap-northeast-2.rds.amazonaws.com/petmily
    username: user
    password: PetmilyProject123!
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:tcp://localhost/~/petmily
#      username: sa
#      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        #        -> system.out
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/

  messages:
    basename: messages, errors, exception

  profiles:
    active: local

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.trace: trace
#    -> 콘솔

server:
  port: 80
  servlet:
    session:
      timeout: 1800

file:
  dir: /home/petmily/picture/
#  dir: /Users/joojongbum/Desktop/work/project/petmily/src/main/resources/static/picture/