spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@petmily_medium?TNS_ADMIN=/Users/joojongbum/Desktop/work/project/petmily/src/main/resources/static/Wallet_petmily/
    username: ADMIN
    password: PetmilyProject123!
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:tcp://localhost/~/petmily
  #    username: sa
  #    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        #        -> system.out
        format_sql: true

  messages:
    basename: messages, errors, exception

  profiles:
    active: local

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.trace: trace
#    -> 콘솔

server:
  port: 80
  servlet:
    session:
      timeout: 1800

file:
  dir: /Users/joojongbum/Desktop/work/project/petmily/src/main/resources/static/picture/